### ISSUE TITLE
EXAMPLE ISSUE

### ISSUE THREAD

**Issue by fraser-langton** [fraser-langton/QuandooScripter#1]
```
Traceback (most recent call last):
  File "run.py", line 227, in <module>
    main()
  File "run.py", line 26, in main
    new_bookings(quandoo_bookings, archtics_bookings, quandoo_merchants)
  File "run.py", line 64, in new_bookings
    dt = parse(f'{booking["event_date"]} {booking["event_time"]}', dayfirst=True)
  File "C:\Users\Destroyer\Downloads\QuandooScripter-master\QuandooScripter-master\venv\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Destroyer\Downloads\QuandooScripter-master\QuandooScripter-master\venv\lib\site-packages\dateutil\parser\_parser.py", line 652, in parse
    raise ParserError("String does not contain a date: %s", timestr)
dateutil.parser._parser.ParserError: String does not contain a date:
dateutil.parser._parser.ParserError String does not contain a date:   - This is a program error, try to debug
```

[files.zip](https://github.com/fraser-langton/QuandooScripter/files/6088007/files.zip)

**Comment by fraser-langton** [comment]
Fixed
